//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoPractical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile_Details
    {
        public int Id { get; set; }
        public string ModelName { get; set; }
        public Nullable<long> ModelPrice { get; set; }
        public string ModelImage { get; set; }
    }
}
