//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoPractical
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegisteration
    {
        public int AdmissionNo { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public int ApplicationFormNo { get; set; }
        public string CourseName { get; set; }
        public string Semester { get; set; }
        public string Division { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string FatherName { get; set; }
        public string Occupation { get; set; }
        public string MotherName { get; set; }
        public Nullable<long> AnnualIncome { get; set; }
        public string Nationality { get; set; }
        public string Region { get; set; }
        public string BloodGroup { get; set; }
        public string Category { get; set; }
        public string Cast { get; set; }
        public string Quota { get; set; }
        public Nullable<bool> FeesConcession { get; set; }
        public string FeeStructure { get; set; }
        public string MobileNumber { get; set; }
        public string ParentMobileNumber { get; set; }
        public string Address { get; set; }
        public string Percentage10th { get; set; }
        public string Percentage12th { get; set; }
        public Nullable<long> TrasportationCost { get; set; }
        public string HostelName { get; set; }
        public string Marksheet10th { get; set; }
        public string Marksheet12th { get; set; }
        public string SchoolLeaving { get; set; }
        public string ProfilePicture { get; set; }
    }
}
